name: Build EXE for Windows

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openpyxl tkinterdnd2 pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --collect-all tkinterdnd2 bom2.py
        
      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: exe-file
          path: dist/bom2.exe
